version: "3.2"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT_KEY: dev
    restart: unless-stopped
    container_name: symfony-php
    links:
      - mysql
    networks:
      - blog
    ports:
      - 10500:80
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@mysql:3306/blog?serverVersion=5.7

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql
    networks:
      - blog
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - symfony-blog-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin12345
    networks:
      - blog

networks:
  blog:
    driver: overlay

volumes:
  symfony-blog-data:


